Name: Rex::Module::CMS::WP_CLI
Description: Wordpress CLI module for Rex, it permits to manage Wordpress install through the Command-Line Interface
Author: Paulo Graça <info@rcaap.pt>
License: Apache 2.0
Require:
  # dependes on PHP from Recipies
  - Rex/Lang/PHP:
        git: https://github.com/fccn/rex-recipes.git
        branch: "Rex/Lang/PHP"